stages:
    - production

production:
    type: deploy
    stage: production
    image: Dockerfile:latest
    script:
        - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
    only:
        - master