stages:
    - deploy

staging:
  image: ruby:2.3
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY --strategy=git
  only:
    - master