# Generated by Django 2.2.12 on 2020-05-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tale',
            name='TaleName',
            field=models.TextField(default='FefaultTaleName', max_length=50),
        ),
    ]
