# Generated by Django 3.0.5 on 2020-05-02 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Length', models.IntegerField(default=0)),
                ('isFinished', models.BooleanField(default=0)),
                ('dateStarted', models.DateTimeField()),
                ('dateFinished', models.DateTimeField()),
                ('lastAuthorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lastAuthorID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAdded', models.DateTimeField()),
                ('Sentence', models.TextField(max_length=128)),
                ('authorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AuthorID', to=settings.AUTH_USER_MODEL)),
                ('taleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TaleID', to='Tales.Tale')),
            ],
        ),
        migrations.AddIndex(
            model_name='sentence',
            index=models.Index(fields=['taleID', 'authorID'], name='Tales_sente_taleID__541de7_idx'),
        ),
    ]
