# Generated by Django 2.2.12 on 2020-05-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tales', '0002_tale_talename'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Length', models.IntegerField(default=0)),
                ('isFinished', models.BooleanField(default=0)),
                ('dateStarted', models.DateTimeField()),
                ('TaleName', models.TextField(default='FefaultTaleName', max_length=50)),
            ],
        ),
    ]
