# Generated by Django 2.2.12 on 2020-05-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tales', '0003_testdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='tale',
            name='isBeingWritten',
            field=models.BooleanField(default=0),
        ),
    ]
