# Generated by Django 2.2.12 on 2020-05-09 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tales', '0006_remove_tale_authorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='authorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorID', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='taleID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taleID', to='Tales.Tale'),
        ),
        migrations.AlterField(
            model_name='tale',
            name='TaleName',
            field=models.TextField(default='defaultTaleName', max_length=50),
        ),
    ]
