# Generated by Django 2.2.12 on 2020-05-10 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tales', '0007_auto_20200509_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserlessTale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Length', models.IntegerField(default=0)),
                ('isFinished', models.BooleanField(default=0)),
                ('dateStarted', models.DateTimeField()),
                ('dateFinished', models.DateTimeField()),
                ('TaleName', models.TextField(default='defaultTaleName', max_length=50)),
                ('isBeingWritten', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserlessSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAdded', models.DateTimeField()),
                ('Sentence', models.TextField(max_length=128)),
                ('taleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taleID', to='Tales.UserlessTale')),
            ],
        ),
        migrations.AddIndex(
            model_name='userlesssentence',
            index=models.Index(fields=['taleID'], name='Tales_userl_taleID__ab5788_idx'),
        ),
    ]
