# Generated by Django 2.2.12 on 2020-05-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tales', '0008_auto_20200510_0904'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestData',
        ),
        migrations.AlterField(
            model_name='userlesstale',
            name='dateFinished',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
