# Generated by Django 2.2.12 on 2020-05-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tales', '0009_auto_20200510_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tale',
            name='dateFinished',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
